# Generated by Django 4.0.4 on 2023-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='expense',
            field=models.IntegerField(default=0),
        ),
    ]
