# Generated by Django 4.0 on 2023-03-22 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passenger_expense'),
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 16, 26, 32, 345757, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('seat', 'user')},
        ),
    ]
