# Generated by Django 4.0 on 2023-03-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_payment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
