# Generated by Django 4.0 on 2023-03-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('name', 'flight')},
        ),
    ]
